name: Go Code Quality Check

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Check Go Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17' # You can adjust the Go version as needed

      - name: Install dependencies
        run: |
          go get -v -t -d ./...
                                                                                                                                                                                                                                                                                               
      - name: Run go vet
        run: |
          go vet ./...
          VET_EXIT_STATUS=$?
          if [ $VET_EXIT_STATUS -ne 0 ]; then
            echo "go vet found errors, exiting..."
            exit $VET_EXIT_STATUS
          fi

      - name: Check code formatting
        run: |
          gofmt -l -s -w .
          FMT_EXIT_STATUS=$?
          if [ $FMT_EXIT_STATUS -ne 0 ]; then
            echo "gofmt found errors, exiting..."
            exit $FMT_EXIT_STATUS
          fi

    